### ISSUE TITLE
Improve overlay wiki

### ISSUE THREAD

**Issue by MoonDragon-MD** [nkrapivin/stormworkshoptool#1]
Hi, I am doing the translation of the game into Italian. I could use the mod with overlay, on the wiki it's poorly explained and it's not clear how I should do it. 
I have done it this way but it doesn't work:

A) I created a folder called "overlay_ITA" and put it in the installation folder.

B) inside I put the folder "Resource" and the file "overlays.txt" with the following lines:
Resource\INI\texts\english
Resource\INI\interfaces
Resource\Textures\Interfaces\LE\Fonts

It doesn't load though, where did I go wrong?

**Comment by nkrapivin** [comment]
Oh, because you need to put the name of the folder in `overlays.txt`, so you'd put `overlay_ITA`, then all the contents of that folder will be overlaid recursively automatically.

**Comment by MoonDragon-MD** [comment]
I thank you for your answer, it works now. 
I didn't realize that the txt file went outside the folder, and that all subfolders should not be specified.

Thank you and good work
